# Generated by Django 4.2 on 2023-06-08 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='recepe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recepe_name', models.CharField(max_length=150)),
                ('recepe_desc', models.TextField()),
                ('recepe_image', models.ImageField(upload_to='recepe_img')),
            ],
        ),
        migrations.DeleteModel(
            name='receipe',
        ),
    ]
