# Generated by Django 4.2 on 2023-06-11 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0003_recepe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepe',
            name='recepe_view_count',
            field=models.IntegerField(default=1),
        ),
    ]
