# Generated by Django 4.2 on 2023-06-13 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0007_subject_subject_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject_marks',
            name='marks',
            field=models.IntegerField(default=0),
        ),
    ]
