# Generated by Django 4.2 on 2023-06-26 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0009_reportcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcard',
            name='data_of_reportcard_generation',
            field=models.DateField(auto_now_add=True),
        ),
    ]
